### PR TITLE
Fix #431: Get CI tests passing. Includes revert commit bff5520 // PR 428

### LINKED ISSUE #431: Get CI tests passing. Includes revert commit bff5520 // PR 428
Commit https://github.com/oceanprotocol/df-py/commit/bff5520c68ae797ff4d6ef91c864269747369f56 from PR https://github.com/oceanprotocol/df-py/pull/428 seemed to cause breakage.

And, there are other CI failures too.

Steps for this issue:

- [x] revert the changes
- [ ] get CI tests passing (this is the big one!)
- [ ] get it reviewed and approved
- [ ] merge
- [ ] un-close the github issues 425, 426, 427 that the PR was supposed to solve

### PR DESCRIPTION
**Pull request by trentmc**
Fixes #431.

Changes proposed in this PR:

- Undid changes from commit https://github.com/oceanprotocol/df-py/commit/bff5520c68ae797ff4d6ef91c864269747369f56 from PR https://github.com/oceanprotocol/df-py/pull/428
- to see all failing tests: in .github/workflows/test.yml, last line, removed the "-x" option. Result: [4 failing tests](https://github.com/oceanprotocol/df-py/actions/runs/3906725513/jobs/6675206269)
- skip failing tests: the aquarius-related ones in test_query.py. (Will get un-skipped in [#437](https://github.com/oceanprotocol/df-py/issues/437))
- in test.yml: minimize chance of failure from barge not being ready: retry up to 108 times ([like ocean.py](https://github.com/oceanprotocol/ocean.py/blob/main/.github/workflows/pytest.yml))

### CODE REVIEW

**Comment by trentmc** [comment]
My yesterday's commit [bff5520](https://github.com/oceanprotocol/df-py/commit/bff5520c68ae797ff4d6ef91c864269747369f56), from [PR 428](https://github.com/oceanprotocol/df-py/pull/428), caused a new test to be breaking, in test_calcrewards.py. 

The first commit of _this_ PR un-did those changes. Good news, it un-broke the new failure in test_calcrewards.py. However, the CI still failed >=1 other tests.

df-py CI tests were configured to stop as soon as a single test failed. So that I could understand all failures, I changed it to run all tests. 

The result: 4 tests failed. [Here's the log](https://github.com/oceanprotocol/df-py/actions/runs/3906725513/jobs/6675206269). Below are the tests. Note that they're all Aquarius related.
```text
FAILED util/test/test_query.py::test_queryAquariusAssetNames - AssertionError...
FAILED util/test/test_query.py::test_filter_to_aquarius_assets - assert 0 == 3
FAILED util/test/test_query.py::test_filter_dids - assert 0 == 3
FAILED util/test/test_query.py::test_filter_nft_vols_to_Aquarius_assets - ass...
```

More data:

- Before Berkay went on vacation (until end of Jan), he was fighting with test reliability. In Barge, and elsewhere. He created 2-3 issues around that.
- One of Berkay's changes was to change .github/workflows/test.yml such that it used an older version of barge, before instabilities. In that file, you'll see this as "ref: 9cc3a9342a47857a0495309e787462d6c60979e6", where if it used the up-to-date version it would be "ref: main".

**Comment by trentmc** [comment]
Hypothesis: Aquarius is failing because old barge is grabbing a new aquarius, and they're incompatible.

Experimental setup: have df-py use new barge (which more stabilizing changes since Berkay's workaround). [Done here](https://github.com/oceanprotocol/df-py/pull/432/commits/d8c17874637aa8a648b5f6ccdd4bf2de333051b5).

Result: TBD

**Comment by trentmc** [comment]
----

Hypothesis: the test that hung was `test_csvs::test_rewardsinfo()`, because it calls to `network_setup_and_teardown()` which has a `yield`. (Ironically, this is one of the things that I removed in https://github.com/oceanprotocol/df-py/commit/bff5520c68ae797ff4d6ef91c864269747369f56.)

There are three possible ways to test this, from least to most invasive.
1. make CI tests more verbose, reporting each specific test being run. Via test.yml, last line,  "-s" 
2. pytest.skip the test and see if test_csvs hangs
3. remove dependency on `network_setup_and_teardown()`

I'll do (1), because least invasive. [Here's the commit](https://github.com/oceanprotocol/df-py/pull/432/commits/c8c3611383996b40d5ea149d13c56234be90472e).

**Comment by trentmc** [comment]
Goal: better understand how long things are running for. So I can tell that if I've halted something, whether it was hung, or just long-running.

How: print out a timestamp for each unit test being run. Via [this commit](https://github.com/oceanprotocol/df-py/pull/432/commits/bf5db5b1688ed068a7c741957895ca776615f1da).

Run kicked off...

WIP

**Comment by trentmc** [comment]
New learning. ocean.py has had some similar issues of txs hanging:
- Issue: https://github.com/oceanprotocol/ocean.py/issues/1213
- PR: https://github.com/oceanprotocol/ocean.py/pull/1272

The learning: for txs that you're _expecting_ to fail, it could hang unless you set # confirmations to zero in the calling tx dict. 

To fix it:
```python
 {"from": account, "required_confs": 0},
```

**Comment by alexcos20** [comment]
Another stop:  https://github.com/oceanprotocol/df-py/actions/runs/3911612315/jobs/6685200852.  It was taking more than 2 hours.

**Comment by trentmc** [comment]
> Another stop: https://github.com/oceanprotocol/df-py/actions/runs/3911612315/jobs/6685200852. It was taking more than 2 hours.

Thanks. I was about to stop it. And now we have more information to work with:)

**Comment by trentmc** [comment]
**Actions:**

- Change logging from -v to -s, for more verbosity in CI
- set required_confs = 0 for tests with `pytest.raises` (listed above). This should stop hanging on the test that uses it. However we shouldn't expect much yet, since we didn't change `test_small_batch`.
- did _not_ yet set required_confs = 0 for tests with `brownie.reverts` (listed above). 

Then kicked off a job.

**Results:** 

Force-stopped run after 1h 15min.

[Log](https://github.com/oceanprotocol/df-py/actions/runs/3912854527/jobs/6688022841).

- Last test that passed: `util/test/test_dftool.py::test_noarg_commands`
- The test it was on: `test_dispense.py::test_small_batch`. This is the same test that we stopped at before, twice.

**Comment by trentmc** [comment]
**Actions:**

- To test_dispense.py::test_small_batch and dispense.py::dispense(), I added print statements to debug

Then kicked off a job.

**Results:** 

TBD

**Comment by trentmc** [comment]
**Action:**

[For all brownie.reverts() write txs, set required_confs = 0](https://github.com/oceanprotocol/df-py/pull/432/commits/2600906dd321caa05fa9c7d0b0f467eba500a759)

**Result:**

[Log](https://github.com/oceanprotocol/df-py/actions/runs/3914374373/jobs/6691353245).

**Discussion:**

It hung, like before, same way as before.

**Comment by trentmc** [comment]
Action: switch back to old barge

Result: [log](https://github.com/oceanprotocol/df-py/actions/runs/3918141107/jobs/6698348006).

Discussion: it failed. Aquarius errors, and "transaction did not revert"

**Pull request merged**
